name: Build and publish

on:
  push:
    branches: [ "main" ]

env:
  target-registry: "ghcr.io/jakubaakk/mcdc-ws"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      env:
        CGO_ENABLED: 0
      run: go build -v -o mcdc-ws

    - name: Get version
      id: get-version
      run: |
        VERSION=$(cat VERSION)
        echo "::set-output name=VERSION::$VERSION"

    - name: Docker build and tag
      run: |
        docker build --no-cache -t ${{ env.target-registry }}:latest .
        docker tag ${{ env.target-registry }}:latest ${{ env.target-registry }}:${{ steps.get-version.outputs.VERSION }}

    - name: Docker push
      run: |
        docker push ${{ env.target-registry }}:latest
        docker push ${{ env.target-registry }}:${{ steps.get-version.outputs.VERSION }}
